#!/usr/bin/env python
"""Batch QC screening for CE handoff (IPF/ALK5 cycle3).

Implements qchem-workflow "Batch Screening Pipeline" in a lightweight, checkpointed way.

Pipeline per molecule:
1) Input validation: RDKit parse + ETKDG embed (and UFF preopt)
2) DFT opt + frequency: B97-D/def2-SVP (PySCF + geomeTRIC)
3) Property extraction: E_total, HOMO, LUMO, gap, dipole
4) qc_flag per molecule; failures do not stop batch
5) Outputs (checkpointed as we go):
   - exports/qc_results.json
   - exports/batch_audit.json

Notes:
- B97-D here is dispersion-inclusive XC (no external D3 tooling required).
- Frequencies are harmonic; n_imag gate enforced for minima.

"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from rdkit import Chem
from rdkit.Chem import AllChem

from pyscf import gto, dft
from pyscf.hessian import rks as rks_hess
from pyscf.hessian import thermo

import geometric
from pyscf.geomopt.geometric_solver import optimize

HARTREE_TO_EV = 27.211386245988
BOHR_TO_ANG = 0.529177210903

# --- Batch config (speed / stability trade-off) ---
XC = "b97-d"  # dispersion-inclusive XC in libxc
BASIS = "def2-svp"
GRID_LEVEL = 4
SCF_CONV_TOL = 1e-9
SCF_MAX_CYCLE = 200

OPT_MAXITER = 200

# TD/Excited-state not requested in this batch.


@dataclass
class MoleculeInput:
    mol_id: str
    smiles: str
    charge: int
    spin: int
    vina_score: Optional[float] = None
    hinge_hbond: Optional[bool] = None


def _now() -> float:
    return time.time()


def rdkit_embed(smiles: str, seed: int = 0xC0FFEE) -> Tuple[np.ndarray, List[str]]:
    """Return (coords_angstrom Nx3, symbols list). Raises on failure."""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError("RDKit MolFromSmiles failed")
    mol = Chem.AddHs(mol)

    params = AllChem.ETKDGv3()
    params.randomSeed = int(seed)
    # RDKit versions differ; do not assume params has maxAttempts
    cid = AllChem.EmbedMolecule(mol, params)
    if cid < 0:
        raise RuntimeError("RDKit ETKDG embedding failed")

    # quick MMFF/UFF relaxation (fail-soft)
    try:
        if AllChem.MMFFHasAllMoleculeParams(mol):
            AllChem.MMFFOptimizeMolecule(mol, maxIters=500)
        else:
            AllChem.UFFOptimizeMolecule(mol, maxIters=500)
    except Exception:
        pass

    conf = mol.GetConformer()
    symbols = [a.GetSymbol() for a in mol.GetAtoms()]
    coords = np.array(conf.GetPositions(), dtype=float)
    return coords, symbols


def xyz_text(symbols: List[str], coords_ang: np.ndarray) -> str:
    lines = [str(len(symbols)), "generated by batch_qc_cycle3.py"]
    for s, (x, y, z) in zip(symbols, coords_ang):
        lines.append(f"{s:2s} {x: .10f} {y: .10f} {z: .10f}")
    return "\n".join(lines) + "\n"


def pyscf_mol_from_xyz(xyz: str, basis: str, charge: int, spin: int) -> gto.Mole:
    # xyz is XYZ format; pyscf expects atom string or list
    lines = [ln.strip() for ln in xyz.strip().splitlines()]
    body = lines[2:]
    atom_lines = []
    for ln in body:
        if not ln:
            continue
        sym, x, y, z = ln.split()[:4]
        atom_lines.append([sym, (float(x), float(y), float(z))])
    mol = gto.M(
        atom=atom_lines,
        unit="Angstrom",
        basis=basis,
        charge=charge,
        spin=spin,
        verbose=0,
    )
    return mol


def run_scf(mol: gto.Mole) -> dft.RKS:
    mf = dft.RKS(mol)
    mf.xc = XC
    mf.grids.level = GRID_LEVEL
    mf.conv_tol = SCF_CONV_TOL
    mf.max_cycle = SCF_MAX_CYCLE
    mf.kernel()
    return mf


def run_dft_opt(symbols: List[str], coords_ang: np.ndarray, charge: int, spin: int) -> str:
    """Run geomeTRIC optimization via PySCF's geometric_solver wrapper.

    Returns optimized geometry as XYZ text.
    """
    init_xyz = xyz_text(symbols, coords_ang)
    mol0 = pyscf_mol_from_xyz(init_xyz, BASIS, charge, spin)
    mf0 = run_scf(mol0)
    if not mf0.converged:
        raise RuntimeError("SCF did not converge at initial geometry; cannot start optimization")

    # pyscf wrapper runs geomeTRIC under the hood
    mol_opt = optimize(mf0, maxsteps=OPT_MAXITER)

    # PySCF stores internal coords in Bohr
    coords_opt_ang = np.array(mol_opt.atom_coords(), dtype=float) * BOHR_TO_ANG
    symbols_opt = [mol_opt.atom_symbol(i) for i in range(mol_opt.natm)]
    return xyz_text(symbols_opt, coords_opt_ang)


def harmonic_freqs_cm1(mf: dft.RKS) -> Tuple[np.ndarray, Dict[str, Any]]:
    """Return (freqs_cm1, thermo_dict) using PySCF harmonic analysis."""
    hobj = rks_hess.Hessian(mf)
    hess_ao = hobj.kernel()

    # thermo.harmonic_analysis expects mol + hess in AO units.
    out = thermo.harmonic_analysis(mf.mol, hess_ao)
    freqs = np.array(out["freq_wavenumber"], dtype=float)
    return freqs, out


def extract_orbital_props(mf: dft.RKS) -> Tuple[float, float, float]:
    mo_e = np.array(mf.mo_energy)
    occ = np.array(mf.mo_occ)
    homo = float(np.max(mo_e[occ > 0]))
    lumo = float(np.min(mo_e[occ == 0]))
    gap_ev = float((lumo - homo) * HARTREE_TO_EV)
    return homo, lumo, gap_ev


def dipole_debye(mf: dft.RKS) -> float:
    # Electronic dipole + nuclear dipole in a.u.
    # PySCF returns dipole in a.u.; convert to Debye.
    from pyscf import scf as scf_mod

    dip = scf_mod.hf.dip_moment(mf.mol, mf.make_rdm1(), unit="Debye")
    # magnitude
    return float(np.linalg.norm(np.array(dip)))


def qc_flag_from_status(
    *,
    embed_ok: bool,
    scf_ok: bool,
    opt_ok: bool,
    freq_ok: bool,
    n_imag: Optional[int],
) -> str:
    if not embed_ok:
        return "EMBED_FAIL"
    if not opt_ok:
        return "OPT_FAIL"
    if not scf_ok:
        return "SCF_FAIL"
    if not freq_ok or n_imag is None:
        return "FREQ_FAIL"
    if n_imag != 0:
        return "IMAG_FREQ"
    return "PASS"


def safe_write_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(obj, indent=2))
    tmp.replace(path)


def main() -> None:
    # Workspace-root relative paths (portable for open-source release)
    # Repo root is two levels up from this file: research/ipf_alk5_cycle3_qc/batch_qc_cycle3.py
    repo_root = Path(__file__).resolve().parents[2]
    in_path = repo_root / "imports/qc_handoff_cycle3.json"
    exports = repo_root / "exports"
    exports.mkdir(parents=True, exist_ok=True)

    ckpt_dir = exports / "checkpoints_cycle3"
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    data = json.loads(in_path.read_text())
    mols_in = [MoleculeInput(**m) for m in data["molecules"]]

    audit: Dict[str, Any] = {
        "source": in_path.as_posix(),
        "project": data.get("project"),
        "started_at": _now(),
        "method": {
            "xc": XC,
            "basis": BASIS,
            "grid_level": GRID_LEVEL,
            "scf_conv_tol": SCF_CONV_TOL,
            "software": {"pyscf": __import__("pyscf").__version__, "geometric": geometric.__version__},
        },
        "molecules": {},
    }

    results: List[Dict[str, Any]] = []

    for m in mols_in:
        t0 = _now()
        mol_audit: Dict[str, Any] = {"mol_id": m.mol_id, "smiles": m.smiles, "events": []}

        # Checkpoint skip if already done
        ckpt_json = ckpt_dir / f"{m.mol_id}.json"
        if ckpt_json.exists():
            prev = json.loads(ckpt_json.read_text())
            if prev.get("status") == "DONE":
                results.append(prev["qc_result"])
                audit["molecules"][m.mol_id] = prev["audit"]
                continue

        embed_ok = False
        scf_ok = opt_ok = freq_ok = False
        n_imag = None
        qc_res: Dict[str, Any] = {
            "mol_id": m.mol_id,
            "smiles": m.smiles,
            "charge": m.charge,
            "spin": m.spin,
            "method": f"{XC}/{BASIS}",
            "software": {"pyscf": __import__("pyscf").__version__},
        }

        try:
            # 1) RDKit embed
            mol_audit["events"].append({"t": _now(), "step": "embed_start"})
            coords, symbols = rdkit_embed(m.smiles)
            init_xyz = xyz_text(symbols, coords)
            (ckpt_dir / f"{m.mol_id}_init.xyz").write_text(init_xyz)
            embed_ok = True
            mol_audit["events"].append({"t": _now(), "step": "embed_ok", "natoms": len(symbols)})

            # 2) DFT opt (geomeTRIC via PySCF wrapper)
            mol_audit["events"].append({"t": _now(), "step": "opt_start"})
            opt_xyz = run_dft_opt(symbols, coords, m.charge, m.spin)
            opt_xyz_path = ckpt_dir / f"{m.mol_id}_opt.xyz"
            opt_xyz_path.write_text(opt_xyz)
            opt_ok = True
            mol_audit["events"].append({"t": _now(), "step": "opt_ok"})

            # 2b) SCF at optimized geometry (gate)
            mol = pyscf_mol_from_xyz(opt_xyz, BASIS, m.charge, m.spin)
            mf = run_scf(mol)
            if not mf.converged:
                raise RuntimeError("SCF gate failed on optimized geometry")
            scf_ok = True
            qc_res["E_total_Ha"] = float(mf.e_tot)

            homo, lumo, gap_ev = extract_orbital_props(mf)
            qc_res["HOMO_Ha"] = homo
            qc_res["LUMO_Ha"] = lumo
            qc_res["gap_eV"] = gap_ev
            qc_res["dipole_D"] = dipole_debye(mf)

            # 3) Frequency analysis
            mol_audit["events"].append({"t": _now(), "step": "freq_start"})
            freqs, th = harmonic_freqs_cm1(mf)
            freq_ok = True
            n_imag = int(np.sum(freqs < -1.0))
            qc_res["n_imag"] = n_imag
            qc_res["min_freq_cm1"] = float(np.min(freqs))
            # ZPE from thermo dict: 'ZPE' in Hartree
            if "ZPE" in th:
                qc_res["ZPE_Ha"] = float(th["ZPE"])
                qc_res["ZPE_kcalmol"] = float(th["ZPE"] * 627.509474)
            mol_audit["events"].append({"t": _now(), "step": "freq_ok", "n_imag": n_imag})

        except Exception as ex:
            mol_audit["events"].append({"t": _now(), "step": "error", "error": repr(ex)})

        qc_flag = qc_flag_from_status(embed_ok=embed_ok, scf_ok=scf_ok, opt_ok=opt_ok, freq_ok=freq_ok, n_imag=n_imag)
        qc_res["qc_flag"] = qc_flag
        qc_res["vina_score"] = m.vina_score
        qc_res["hinge_hbond"] = m.hinge_hbond
        qc_res["walltime_s"] = float(_now() - t0)

        # Write per-molecule checkpoint
        ckpt_payload = {
            "status": "DONE",
            "qc_result": qc_res,
            "audit": mol_audit,
        }
        safe_write_json(ckpt_json, ckpt_payload)

        results.append(qc_res)
        audit["molecules"][m.mol_id] = mol_audit

        # Batch-level checkpoints after each molecule
        safe_write_json(exports / "qc_results.json", {"project": data.get("project"), "results": results})
        safe_write_json(exports / "batch_audit.json", audit)

    audit["finished_at"] = _now()
    safe_write_json(exports / "batch_audit.json", audit)


if __name__ == "__main__":
    main()
